### ISSUE TITLE
无法登录呀

### ISSUE THREAD

**Issue by luiguangguan** [orangelckc/bili-bot#13]
![image](https://github.com/orangelckc/bili-bot/assets/20753694/c70804a4-af3d-4841-8bf6-2a9bdabce221)
最新版就这样，一个二维码闪一下就出现登录成功，一直留在这个画面

另外，这个最新安装的版本，就得版本还有保留，不是直接升级？

**Comment by orangelckc** [comment]
上周接口改了，我还没来的及发布😓
这个没做自动更新，更新需要一个更新服务器的，麻烦，直接覆盖安装就好，本地的数据不会丢失的

**Comment by orangelckc** [comment]
@luiguangguan 新版本发了，更新一下 [v1.2.10](https://github.com/orangelckc/bili-bot/releases/tag/v1.2.10)
